"""Generate a substitute W-9 PDF from a BA's stored profile data.

The IRS allows substitute W-9 forms as long as they include the same
information, certifications, and signature requirements. We render the form
on demand (no persistent PDF storage) so plaintext TINs only exist in memory.
"""

from datetime import date
from io import BytesIO

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

ENTITY_TYPE_LABELS: dict[str, str] = {
    "individual": "Individual / sole proprietor",
    "sole_proprietor": "Sole proprietor",
    "llc_single": "LLC (single-member, disregarded entity)",
    "llc_partnership": "LLC (taxed as partnership)",
    "llc_corp": "LLC (taxed as corporation)",
    "c_corp": "C corporation",
    "s_corp": "S corporation",
    "partnership": "Partnership",
    "other": "Other",
}


def _format_tin(tin: str, tin_type: str | None) -> str:
    digits = "".join(c for c in tin if c.isdigit())
    if tin_type == "ssn" and len(digits) == 9:
        return f"{digits[0:3]}-{digits[3:5]}-{digits[5:9]}"
    if tin_type == "ein" and len(digits) == 9:
        return f"{digits[0:2]}-{digits[2:9]}"
    return digits


def generate_w9_pdf(
    *,
    legal_name: str,
    business_name: str | None,
    entity_type: str,
    address_line1: str,
    address_line2: str | None,
    city: str,
    state: str,
    zip_code: str,
    tin_plaintext: str,
    tin_type: str,
    signature_name: str,
    signature_date: date,
) -> bytes:
    """Render a substitute W-9 PDF with the BA's data. Returns PDF bytes."""
    buf = BytesIO()
    pdf = canvas.Canvas(buf, pagesize=LETTER)
    width, height = LETTER

    margin_x = 0.75 * inch
    y = height - 0.75 * inch

    # Header
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(margin_x, y, "Form W-9 (Substitute)")
    pdf.setFont("Helvetica", 9)
    pdf.drawRightString(
        width - margin_x, y, "Request for Taxpayer Identification Number and Certification"
    )
    y -= 0.3 * inch
    pdf.setFont("Helvetica-Oblique", 8)
    pdf.drawString(
        margin_x,
        y,
        "Substitute form generated by the NMB Media Staffing Portal. "
        "Contains all information required by the IRS official Form W-9.",
    )
    y -= 0.35 * inch

    # Section: name + entity
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(margin_x, y, "1. Name (as shown on your income tax return)")
    y -= 0.2 * inch
    pdf.setFont("Helvetica", 11)
    pdf.drawString(margin_x + 0.1 * inch, y, legal_name)
    y -= 0.3 * inch

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(margin_x, y, "2. Business name / disregarded entity name (if different from above)")
    y -= 0.2 * inch
    pdf.setFont("Helvetica", 11)
    pdf.drawString(margin_x + 0.1 * inch, y, business_name or "—")
    y -= 0.3 * inch

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(margin_x, y, "3. Federal tax classification")
    y -= 0.2 * inch
    pdf.setFont("Helvetica", 11)
    pdf.drawString(
        margin_x + 0.1 * inch, y, ENTITY_TYPE_LABELS.get(entity_type, entity_type)
    )
    y -= 0.4 * inch

    # Address
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(margin_x, y, "5. Address (number, street, and apt. or suite no.)")
    y -= 0.2 * inch
    pdf.setFont("Helvetica", 11)
    addr = address_line1
    if address_line2:
        addr += f", {address_line2}"
    pdf.drawString(margin_x + 0.1 * inch, y, addr)
    y -= 0.3 * inch

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(margin_x, y, "6. City, state, and ZIP code")
    y -= 0.2 * inch
    pdf.setFont("Helvetica", 11)
    pdf.drawString(margin_x + 0.1 * inch, y, f"{city}, {state} {zip_code}")
    y -= 0.45 * inch

    # Part I: TIN
    pdf.setFillColorRGB(0.92, 0.92, 0.92)
    pdf.rect(margin_x, y - 0.15 * inch, width - 2 * margin_x, 0.25 * inch, fill=1, stroke=0)
    pdf.setFillColorRGB(0, 0, 0)
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(margin_x + 0.1 * inch, y - 0.05 * inch, "Part I — Taxpayer Identification Number (TIN)")
    y -= 0.5 * inch

    pdf.setFont("Helvetica-Bold", 10)
    label = "Social Security Number (SSN)" if tin_type == "ssn" else "Employer Identification Number (EIN)"
    pdf.drawString(margin_x, y, label)
    y -= 0.22 * inch
    pdf.setFont("Helvetica", 13)
    pdf.drawString(margin_x + 0.1 * inch, y, _format_tin(tin_plaintext, tin_type))
    y -= 0.5 * inch

    # Part II: Certification
    pdf.setFillColorRGB(0.92, 0.92, 0.92)
    pdf.rect(margin_x, y - 0.15 * inch, width - 2 * margin_x, 0.25 * inch, fill=1, stroke=0)
    pdf.setFillColorRGB(0, 0, 0)
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(margin_x + 0.1 * inch, y - 0.05 * inch, "Part II — Certification")
    y -= 0.4 * inch

    cert_lines = [
        "Under penalties of perjury, I certify that:",
        "1. The number shown on this form is my correct taxpayer identification number "
        "(or I am waiting for a number to be issued to me); and",
        "2. I am not subject to backup withholding because (a) I am exempt from backup withholding, or "
        "(b) I have not been notified by the IRS that I am subject to backup withholding as a result of a",
        "    failure to report all interest or dividends, or (c) the IRS has notified me that I am no longer "
        "subject to backup withholding; and",
        "3. I am a U.S. citizen or other U.S. person; and",
        "4. The FATCA code(s) entered on this form (if any) indicating that I am exempt from FATCA "
        "reporting is correct.",
    ]
    pdf.setFont("Helvetica", 8.5)
    for line in cert_lines:
        pdf.drawString(margin_x, y, line)
        y -= 0.16 * inch
    y -= 0.2 * inch

    # Signature
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(margin_x, y, "Signature of U.S. person")
    pdf.drawString(width - 2.5 * inch, y, "Date")
    y -= 0.05 * inch
    pdf.line(margin_x, y, margin_x + 3.5 * inch, y)
    pdf.line(width - 2.5 * inch, y, width - margin_x, y)
    y -= 0.2 * inch
    pdf.setFont("Helvetica-Oblique", 11)
    pdf.drawString(margin_x + 0.1 * inch, y, f"/s/ {signature_name}")
    pdf.drawString(width - 2.5 * inch + 0.1 * inch, y, signature_date.strftime("%Y-%m-%d"))

    # Footer
    pdf.setFont("Helvetica", 7)
    pdf.setFillColorRGB(0.5, 0.5, 0.5)
    pdf.drawCentredString(
        width / 2,
        0.4 * inch,
        "Substitute W-9 generated electronically — equivalent to the signed paper form per IRS Pub. 1167.",
    )

    pdf.showPage()
    pdf.save()
    return buf.getvalue()
